### ISSUE TITLE
Critical ABORT on HEAD failure

### ISSUE THREAD

**Issue by elserguito** [commixproject/commix#374]
Some built-in HTTP servers on network appliances do not support HEAD HTTP request.

Therefore, Commix scan is interrupted on TCP connection reset after HEAD request:
- HTTP GET / : 200 OK
- HTTP HEAD / : TCP RESET
`Critical: The target host is not responding. Please ensure that is up and try again.`
I think the HEAD request should be optional, and the scan should continue even after HEAD failure.

**Comment by stasinopoulos** [comment]
Fixes https://github.com/commixproject/commix/commit/5548fff707e48358d24e51bea54571335c0bf038

**Comment by elserguito** [comment]
Thank you for the fix.
Hopelessly, the appliance I've been testing on has been upgraded, and has now additional protection.
It has now some randomly generated parameter ID for each request...

When I run commix, I get "[x] Critical: 104." error.
What does it mean?

**Comment by stasinopoulos** [comment]
Hello @elserguito, regarding the randomly generated parameter ID for each request, you must combine commix with [**Macros**](https://portswigger.net/burp/documentation/desktop/options/sessions/macro-editor) in **Burp Suite** (which are a great way to bypass these measures in order to carry out automated testing). Finally, "[x] Critical: 104." error means  "**Connection reset by peer**".
