### ISSUE TITLE
error  critical 13.

### ISSUE THREAD

**Issue by zero-plus** [commixproject/commix#621]
___   ___     ___ ___     ___ ___ /\_\   __  _   
 /`___\ / __`\ /' __` __`\ /' __` __`\/\ \ /\ \/'\  v3.2-dev#84
/\ \__//\ \/\ \/\ \/\ \/\ \/\ \/\ \/\ \ \ \\/>  </  
\ \____\ \____/\ \_\ \_\ \_\ \_\ \_\ \_\ \_\/\_/\_\ https://commixproject.com
 \/____/\/___/  \/_/\/_/\/_/\/_/\/_/\/_/\/_/\//\/_/ (@commixproject)

+--
Automated All-in-One OS Command Injection Exploitation Tool
Copyright © 2014-2021 Anastasios Stasinopoulos (@ancst)
+--

(!) Legal disclaimer: Usage of commix for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program.

[info] Parsing HTTP request using the 'rce.txt' file.           
[info] Resolving hostname 'www.***.***'.
[info] Testing connection to the target URL.  
[critical] 13.

**Comment by stasinopoulos** [comment]
Hey @zero-plus and thanks for your bug report.
Due to the fact that I am not able to reproduce the error, kindly provide provide me with more information about this bug.

**Comment by leostat** [comment]
Try setting the output dir (--output-dir), I had the same and the "13" is from perm denied, but as its a touple it was only printing 13!

**Comment by stasinopoulos** [comment]
@leostat @zero-plus  kindly both paste an example exiting with "[critical] 13."

**Comment by zero-plus** [comment]
This error is not only for some special commands. Any simple commix commands that I provide, returns with this error. for example 
- commix  -u  "https://google.com"
btw I'm on the parrot os and after updating with git clone the latest repository I got this error.

**Comment by leostat** [comment]
Sorry that would have helped wouldnt it 😅 , for example on the box Luanne on HTB, 

`
/usr/bin/python3.9 /usr/share/commix/commix.py -u http://10.10.10.218/ -v4

[warning] Python version 3.9.1+ detected. You are advised to use Python version 2.7.x.
                                      __           
   ___   ___     ___ ___     ___ ___ /\_\   __  _   
 /`___\ / __`\ /' __` __`\ /' __` __`\/\ \ /\ \/'\  v3.1-stable
/\ \__//\ \/\ \/\ \/\ \/\ \/\ \/\ \/\ \ \ \\/>  </  
\ \____\ \____/\ \_\ \_\ \_\ \_\ \_\ \_\ \_\/\_/\_\ https://commixproject.com
 \/____/\/___/  \/_/\/_/\/_/\/_/\/_/\/_/\/_/\//\/_/ (@commixproject)

+--
Automated All-in-One OS Command Injection and Exploitation Tool
Copyright © 2014-2020 Anastasios Stasinopoulos (@ancst)
+--

(!) Legal disclaimer: Usage of commix for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program.

[debug] Creating HTTP requests opener object.
[info]  X Checking connection to the target URL. 
[traffic] HTTP request:
GET / HTTP/1.1
Accept-Encoding: identity
Host: 10.10.10.218
User-Agent: commix/v3.1-stable (https://commixproject.com)
Accept: */*
Connection: close
[traffic] HTTP response (200):
Server: nginx/1.19.0
Date: Sat, 20 Mar 2021 19:17:54 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: close
URI: http://10.10.10.218/

{"code": 200, "message": "Censord for spoliers."}
[critical] 13.`


Process finished with exit code 0
`
After poking a breakpoint on print_cricial_msg and following it back, the caller for me was src/core/main.py line number 906, which then jumps to the os.mkdir on line 339 causing the exception [Errno 13] Permission denied: '.output' . , this triggers the exception handler as below:
`
except OSError as err_msg:
      try:
        error_msg = str(err_msg.args[0]).split("] ")[1] + "."
      except IndexError:
        error_msg = str(err_msg.args[0]) + "."
      print(settings.print_critical_msg(error_msg))
      raise SystemExit()
`
This then gets stringified. The value in err_msg.args is
  (13, 'Permission denied') 

so instead something like this may work to print more verbosity (but im bad at python so maybe not? :D ) 
`
except OSError as err_msg:
      try:
        error_msg = ' '.join(map(str, err_msg.args)) + err_msg.filename
      except Exception as e:
        error_msg = str(e) + ' ' + str(err_msg.args[0]) + "."
`

which then prints
`[Errno 13] Permission denied: '/root/ahh'`

Or the wider exception which triggers it + the old beahvior incase thats a python2 ism

**Comment by stasinopoulos** [comment]
Hey @leostat thanks for the comprehensive analysis on that issue. I would like to inform you that i managed to reproduce and verify the "[critical] 13" error on the latest dev version. Regarding the "endless loop" issue that you mentioned, please take a look at: https://github.com/commixproject/commix/issues/552. Finally fixes for both issues are on queue, and will be uploaded (hopefully!) in the next few days.

**Comment by zero-plus** [comment]
Thanks a lot. 
Best regards

**Comment by zero-plus** [comment]
I think it's better to close this issue

**Comment by zero-plus** [comment]
I just found where the problem was from and I think it's necessary to share it with you.
On the parrotOs security, commix is installed in the /usr/share/commix  folder. I manually deleted the whole folder and git cloned it into that folder. Here is where the problem beggins.
parrot by default uses  python3 to run programs. How ever I know that Commix  is on py 2.7.
the first thing That i've done is to manually run commix by terminal. (no python3 ).
And then I found that there is another cause of the problem that it's lack of privilege. so I add sudo add the beginning of the command.
And finally wooow. problem solved.
thanks for your attention :)

**Comment by zero-plus** [comment]
Example of the final successful command:
sudo python commix.py -r /home/myusername/Desktop/commix.txt

**Comment by stasinopoulos** [comment]
This is not a problem regarding commix :)

**Comment by zero-plus** [comment]
I think it is.
not only this will happen for a wide variety of users who  uses commix in parrot but  also the error that commix provided for this was not relevant at all.
critical 13 !!  what's that !!!
Anyway you may be able to handle err better

**Comment by stasinopoulos** [comment]
Yep i agree on that, and I' ll handle the "critical 13" error (as i mentioned in previous comment).
