### ISSUE TITLE
Original Commix ?

### ISSUE THREAD

**Issue by Anthonymcqueen21** [commixproject/commix#673]
Hello, is there anyway to work with my original commix that came with Kali-Linux rather than alternatives like:

- Commix-Master 
- Git Clone version

Or are they all the same and will deliver the same result regardless, i just want to make sure because i don't understand why my original commix that came with kali-linux is giving me directory issues.
![Screenshot from 2021-09-22 06-14-04](https://user-images.githubusercontent.com/23253941/134350386-42dc5380-71da-44ee-b9d5-16f31bbba9c1.png)

**Comment by stasinopoulos** [comment]
Similar with https://github.com/commixproject/commix/issues/670

**Comment by Anthonymcqueen21** [comment]
I don't understand, so you're telling me i need to clone or use the master version and not the one provided with the Parrot OS or Kali-Linux ?

**Comment by christophelimpalair** [comment]
@Anthonymcqueen21 you're running `python3 commix.py` in a directory that doesn't contain commix. If you're trying to use the version included in kali, run commix using `commix -h` instead. Otherwise, if you're trying to use a commix version you downloaded, you first need to navigate in the directory that contains the `commix.py` file.
