### ISSUE TITLE
option sleep 

### ISSUE THREAD

**Issue by Hussienx** [commixproject/commix#98]
hello 
i think  6s  is large 
i hope  to If you put the option, the number of seconds

**Comment by Hussienx** [comment]
and 
threads

**Comment by stasinopoulos** [comment]
Hello @Hussienx, in order to change default time delays use the following options:
`    --delay=DELAY       Seconds to delay between each HTTP request.`
`    --time-sec=TIMESEC  Seconds to delay the OS response (Default 1).`

Moreover, there is already an [open issue](https://github.com/commixproject/commix/issues/67) regarding the Multi-thread support.
